MarvelAPI/Models/Hero.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarvelAPI.Models
{
    public class Hero
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string WikiUrl { get; set; }
    }
}

MarvelAPI/Models/Paginacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarvelAPI.Models
{
    public class Pagination
    {
        public int TotalPages { get; set; }
        public int CurrentPage { get; set; }
    }
}

MarvelAPI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MarvelAPI.Models;

namespace MarvelAPI.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View() ;
        }
    }
}

MarvelAPI/Controllers/MarvelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using MarvelAPI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MarvelAPI.Controllers
{
    public class MarvelController : Controller
    {
        [HttpGet]
        public IActionResult Index(int page)
        {
            try
            {
                return View(GetHeroes(page));
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        private List<Hero> GetHeroes(int page)
        {
            int pageSize = 15;
            using (HttpClient client = new HttpClient())
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = client.GetAsync(GenerateApiString(page, pageSize)).Result;
                response.EnsureSuccessStatusCode();

                var responseJson = response.Content.ReadAsStringAsync().Result;
                dynamic result = JsonConvert.DeserializeObject(responseJson);
                Pagination(page, Convert.ToInt32(result.data.total), pageSize);

                return LisHeroes(pageSize, result);
            }
        }

        private List<Hero> LisHeroes(int pageSize, dynamic result)
        {
            var herois = new List<Hero>();
            var urlImgNull = "http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg";
            for (var i = 0; i != pageSize; i++)
            {
                Hero hero = new Hero
                {
                    ID = result.data.results[i].id,
                    Name = result.data.results[i].name,
                    Description = result.data.results[i].description,
                    ImageUrl = result.data.results[i].thumbnail.path + "." +
                                       result.data.results[i].thumbnail.extension,
                    WikiUrl = IsNullUrl(result.data.results[i].urls[0].url)
                };

                IsNullImage(herois, urlImgNull, hero);
            }

            return herois;
        }

        private static void IsNullImage(List<Hero> herois, string urlImgNull, Hero hero)
        {
            if (!urlImgNull.Equals(hero.ImageUrl))
            {
                herois.Add(hero);
            }
        }

        private void Pagination(int page, int totalHeroes, int pageSize)
        {
            ViewBag.Paging = new Pagination
            {
                TotalPages = (totalHeroes / pageSize) - 1,
                CurrentPage = page
            };
        }

        public string GenerateApiString(int page, int pageSize)
        {
            var timeStamp = DateTime.Now.Ticks.ToString();
            var orderBy = "name";
            var pagination = (Convert.ToInt16(page) * pageSize);
            var publicKey = "3f0440f49c43779bb3901d4e204fae8b";
            var privateKey = "c4452e7e1b880debb82388fe717973fd18f50f8d";
            var hash = GetHash(timeStamp, publicKey, privateKey);
            //var id = "ID HERO";
            //var name = Uri.EscapeUriString("NAME HERO");

            var responseString = "http://gateway.marvel.com/v1/public/characters?" +
                $"orderBy={orderBy}" +
                $"&limit={pageSize}" +
                $"&offset={pagination}" +
                $"&ts={timeStamp}" +
                $"&apikey={publicKey}" +
                $"&hash={hash}";
                //$"&id={id}" +
                //$"name={name}";

            return responseString;
        }

        private string GetHash(string ts, string publicKey, string privateKey)
        {
            byte[] bytes = Encoding.UTF8.GetBytes(ts + privateKey + publicKey);
            var gerador = MD5.Create();
            byte[] bytesHash = gerador.ComputeHash(bytes);

            return BitConverter.ToString(bytesHash).ToLower().Replace("-", String.Empty);
        }

        public string IsNullUrl(dynamic resultado)
        {
            return resultado.Equals(null) ? "https://www.marvel.com/" : (string)resultado;
        }

    }
}

MarvelAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<div class="row">
    <div class="text-center cardIndex col-lg-6">
        <div class="card">
            <img class="card-img-top" src="~/images/marvel-logo.jpg" alt="Card Marvel">
            <div class="card-body">
                <h5 class="card-title">RESTful API Marvel</h5>
                <p class="card-text">An exemple using Marvel API RESTful with .NET Core</p>
                @Html.ActionLink("Go!!", "Index", "Marvel", new { id = 0 }, new { @class = "btn btn-xs btn-primary" })
            </div>
        </div>
    </div>

    <div class="text-center cardIndex col-lg-6">
        <div class="card">
            <img class="card-img-top" src="~/images/gihub.png" alt="Card GitHub">
            <div class="card-body">
                <h5 class="card-title">API Project and Documentation</h5>
                <p class="card-text">Take a look at the implementation with .NET Core API avaliable at my GitHub</p>
                <a href="https://github.com/luangrezende/MarvelApi-DotNetCore" class="btn btn-sm btn-secondary" id="btnGitHub">Access!</a>
            </div>
        </div>
    </div>

</div>

MarvelAPI/Views/Marvel/Index.cshtml
@model List<Hero>
@{
    ViewData["Title"] = "Api Marvel";
}

<h2>Marvel</h2>

@* PAGINACAO *@
<div>
    <nav aria-label="Page Navigation">
        <ul class="pagination">
            @if (ViewBag.Paging.CurrentPage == 0)
            {
                <li class="page-item"><a class="page-link">Previous</a></li>
                <li class="page-item"><a class="page-link" href="@Url.Action("Index", new { page = ViewBag.Paging.CurrentPage + 1})">Next</a></li>
            }
            else if (ViewBag.Paging.CurrentPage > 0)
            {
                <li class="page-item"><a class="page-link" href="@Url.Action("Index", "Marvel", new { page = ViewBag.Paging.CurrentPage - 1})">Previous</a></li>
                <li class="page-item"><a class="page-link" href="@Url.Action("Index", "Marvel", new { page = ViewBag.Paging.CurrentPage + 1})">Next</a></li>
            }
        </ul>
    </nav>
</div>

@* CARDS *@
<div class="container">
    <div class="row">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Image</th>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Page</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var heroi in Model)
                {
                    <tr>
                        <th scope="row">
                            <img class="img" src="@heroi.ImageUrl" alt="Card image cap">
                        </th>
                        <td>@heroi.Name</td>
                        <td>@heroi.Description</td>
                        <td><a href="@heroi.WikiUrl" class="btn btn-danger btn-sm" target="_blank">Wiki Hero</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

MarvelAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Marvel</title>

    @* CSS *@
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>

<body>
    <nav class="navbar navbar-light bg-light">
        <div class="navbar-brand">
            <img src="~/images/marvel.svg" width="70" height="70" class="d-inline-block align-top" alt="Marvel API">
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>


@* SCRIPTS *@
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>